version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: direct
    ignore:
      - dependency-name: "sass-embedded"
        versions: [">= 1.79.0"]  # prevent deprecation warnings https://github.com/jekyll/jekyll/issues/9686#issuecomment-2362850868
